### ISSUE TITLE
Help For Icon

### ISSUE THREAD

**Issue by SubhamTyagi** [SubhamTyagi/quick-calculation#1]
Could anyone make icon for this app

**Comment by SubhamTyagi** [comment]
@izzySoft Could you boost this?

**Comment by IzzySoft** [comment]
If there's a toot I can boost it, yes. Is there one?

**Comment by SubhamTyagi** [comment]
> If there's a toot I can boost it, yes. Is there one?

Here I creates a new one https://mastodon.technology/@shubhamtyagi/107857244788911933  
Thank you.

**Comment by IzzySoft** [comment]
Boosted :smiley:

**Comment by Donnnno** [comment]
Hi @SubhamTyagi I can help you out!

**Comment by SubhamTyagi** [comment]
> Hi @SubhamTyagi I can help you out!

Welcome

**Comment by Donnnno** [comment]
Do you have already something in mind of what it should be?

**Comment by Donnnno** [comment]
A small thing I tried: 

![image](https://user-images.githubusercontent.com/31142286/158198864-95e92ae0-2ea5-4817-9a5d-d5754f1f10da.png)

_a very fast +_

The colors are based on your in-app colors :)

Let me know what you think about something like this.

**Comment by SubhamTyagi** [comment]
I may be a dumb at icons selection and icon making. You are free to to choose whatever you think best for this app.

**Comment by Donnnno** [comment]
True, good points!
I'll take a look later

**Comment by Donnnno** [comment]
> I may be a dumb at icons selection and icon making. You are free to to choose whatever you think best for this app. 

It's your app, I'm just here to help you out!

**Comment by SubhamTyagi** [comment]
2nd one confirm.

**Comment by Donnnno** [comment]
Cool! I'll try to make a PR soon with the new icon!

**Comment by SubhamTyagi** [comment]
@Donnnno Thank you for your help.
