### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by Neriderc** [SubhamTyagi/quick-calculation#10]
No updates in two years. Two pull requests sitting unmerged since two years ago. No response to issues.

Is this project dead? Anyone planning to fork and continue it?

**Comment by SubhamTyagi** [comment]
Is this app not working for you. Are you want to add some features?  This time I have no free time but in future I will have. I will take care of this asap. Currently I am focusing on my study and also working on porting java codes, xml code of other projects to kotlin and compose.

Thanks

**Comment by Neriderc** [comment]
Thanks for rwplying!

The app works OK. I noticed there are two pull requests that haven't been merged (or closed) from 2 years ago.

I don't mean to pressure you! It just seemed like it might have been abandoned.
