### ISSUE TITLE
Release APK

### ISSUE THREAD

**Issue by IzzySoft** [SubhamTyagi/quick-calculation#4]
Currently, the latest release only has a debug APK attached. Could you please attach a release build (without the debug flag) – or is there a reason requiring the debug build?

**Comment by SubhamTyagi** [comment]
Currently I don't have access to signing keys which was used in signing the old version. Latest version apk was the taken from github CI. Now I have deleted this release whenever I get access to signing keys I will publish the release build.

**Comment by IzzySoft** [comment]
Ouch. I hope they are not lost but just on a different machine you currently cannot access? Because a different signature would mean users had to re-install. Whishing you luck to get access back soon!

**Comment by SubhamTyagi** [comment]
Keys are not lost, I have not access to that machine which is storing them.

**Comment by SubhamTyagi** [comment]
@IzzySoft new version is released with old signing keys( finally I have access to them 😁)
Thanks

**Comment by IzzySoft** [comment]
Great, thanks! I'm just puzzled that v1.2 is already in my repo since June 4th – while your tag was just created 4 hours ago…

Btw: may I suggest a slight correction to your `full_description.txt` in Fastlane?

```markdown
Improve your math calculation speed with this app.

<b>Features:</b>

- Addition, Multiplication, Subtractions, Division, Simplification, Simplification Advance, Miscellaneous.
- Custom Range for numbers.
- Timer (30s to 10 minutes).
- Numbers are generated randomly in Custom Range provided by you.
```

(removing the empty last bullet point, removing obsolete spaces around the bullet points – and converting the markdown h2 into an HTML bold – and a small grammar fix) This would render properly at Play, F-Droid and with my repo (where I had fixed it manually). That done, I'd enable it to be refreshed with future releases, so you're in control how your app is described in my repo.
