### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by se34k** [SubhamTyagi/quick-calculation#5]
As soon as I start the app from the launcher, it crashes, with Android displaying »Quick calculation keeps stopping«.

My device: Google Pixel 3a
Operating system: Android 12.1 with May 5th Security Patch

**Comment by Mhdtarek** [comment]
the app works for me i am using a mi note 10 with miui 11

**Comment by Mhdtarek** [comment]
tested it too on a samsung s21

**Comment by latrujil913** [comment]
I am also seeing this crash on my end. I have a Pixel 4a 5G

**Comment by SubhamTyagi** [comment]
Android 12 crash on startup has been fixed in latest release.
